name: Deploy to Server

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  ci_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable pnpm via corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: test
        run: pnpm test

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Build
        run: pnpm build

  deploy_to_main:
    runs-on: ubuntu-latest
    needs: ci_checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/blog
            git pull origin main
            corepack enable
            pnpm install --frozen-lockfile
            pnpm prisma generate
            pnpm build
            pm2 restart blog

  create_pr_from_dev_to_main:
    runs-on: ubuntu-latest
    needs: ci_checks
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge dev to main [Automated]"
          title: "Automated PR: Merge dev to main"
          body: |
            This is an automated pull request to merge changes from `dev` to `main` after `dev` branch CI checks passed.
            Please review and merge.
          branch: "auto-merge-dev-to-main"
          base: "main"
          head: "dev"
          labels: |
            automated-pr
            merge
          draft: false
